import { ThemeConfig } from 'antd/es/config-provider/context';

export const theme: ThemeConfig = {
    token: {
        colorPrimary: '#634e8f',
        sizeStep: 4,
        sizeUnit: 4,
        wireframe: false,
        colorPrimaryText: '#563599',
        colorPrimaryBg: '#EEEBF5',

        // Menu navigation item
        colorPrimaryBgHover: '#EEEBF5',

        colorPrimaryBorder: '#FA541C',
        colorPrimaryHover: '#59477E',
        colorPrimaryActive: '#493A6A',
        colorPrimaryTextHover: '#FA541C',
        colorPrimaryTextActive: '#462786',
        colorSuccessBg: '#E8FBF4',
        colorSuccessBgHover: '#FA541C',
        colorSuccessBorder: '#C0E8DA',
        colorSuccessBorderHover: '#FA541C',
        colorSuccessHover: '#FA541C',
        colorSuccess: '#8dd9be',
        colorSuccessActive: '#FA541C',
        colorSuccessTextHover: '#FA541C',
        colorSuccessText: '#FA541C',
        colorSuccessTextActive: '#FA541C',
        colorWarningBg: '#FEF6E8',
        colorWarningBgHover: '#FA541C',
        colorWarningBorder: '#f7e1b5',
        colorWarningBorderHover: '#FA541C',
        colorWarningHover: '#FA541C',
        colorWarningActive: '#FA541C',
        colorWarningTextHover: '#FA541C',
        colorWarningText: '#FA541C',
        colorWarningTextActive: '#FA541C',
        colorErrorBgHover: '#3ebb00',
        colorErrorBorderHover: '#E73D4E',
        colorErrorHover: '#F35969',
        colorErrorActive: '#F35969',
        colorErrorTextHover: '#3ebb00',
        colorErrorText: '#3ebb00',
        colorErrorTextActive: '#3ebb00',
        colorError: '#F57A87',
        colorErrorBg: '#fff3f5',
        colorErrorBorder: '#FFD7DE',
        colorInfoBgHover: '#FA541C',
        colorInfoBorderHover: '#FA541C',

        // base <a> color
        colorInfoText: '#563599',
        colorInfoHover: '#563599',
        colorInfoActive: '#563599',

        colorInfoTextHover: '#FA541C',
        colorInfoTextActive: '#FA541C',
        colorInfoBg: '#ffffff',
        colorInfoBorder: '#CD93E1',
        colorInfo: '#CD93E1',
        colorText: '#1a1a1a',
        colorTextSecondary: '#000000',
        colorTextTertiary: '#1a1a1a',
        colorTextQuaternary: '#cccccc',
        colorBorder: '#dddddd',
        colorBorderSecondary: '#eeeeee',
        colorFill: '#EEEBF5',
        colorFillSecondary: '#E6E1F0',
        colorFillTertiary: '#ffffff',
        colorBgContainer: '#ffffff',
        colorBgElevated: '#ffffff',
        colorBgLayout: '#ffffff',
        colorBgSpotlight: '#372D3C',
        colorFillQuaternary: '#ffffff',
        fontSizeXL: 0,
        fontSizeHeading1: 0,
        fontSizeHeading2: 0,
        fontSizeHeading3: 24,
        fontSizeHeading4: 20,
        fontSizeHeading5: 16,
        lineHeight: 1.6,
        lineHeightLG: 1.5,
        lineHeightHeading1: 1.2,
        borderRadius: 2,
        borderRadiusXS: 2,
        colorBgMask: '#FA541C',
    },
    components: {
        Button: {
            colorLink: '#563599',
            colorLinkActive: '#462786',
            colorLinkHover: '#462786',
            colorError: '#f57a87',
        },
        Typography: {
            colorLink: '#462786',
            colorLinkActive: '#462786',
            colorLinkHover: '#462786',
        },
        Slider: {
            colorPrimaryBorder: '#563599',
            colorFillContentHover: '#634E8F',
        },
        Select: {
            colorWarningHover: '#E49701',
        },
        Dropdown: {
            colorPrimaryBorder: '#FA541C',
            controlItemBgActiveHover: '#e6e1f0',
            controlItemBgHover: '#f7f7f7',
        },
        DatePicker: {
            colorLink: '#563599',
            colorLinkActive: '#462786',
            colorLinkHover: '#462786',
        },
        Message: {
            colorInfo: '#cd93e1',
        },
        Radio: {
            colorTextDisabled: '#ccc',
        },
    },
};
