import { ThemeConfig } from 'antd/es/config-provider/context';

export const theme: ThemeConfig = {
    token: {
        colorPrimary: '#634e8f',
        sizeStep: 4,
        sizeUnit: 4,
        wireframe: false,
        colorPrimaryText: '#563599',
        colorPrimaryBg: '#EEEBF5',

        // Menu navigation item
        colorPrimaryBgHover: '#EEEBF5',

        colorPrimaryBorder: '#FA541C',
        colorPrimaryHover: '#59477E',
        colorPrimaryActive: '#493A6A',
        colorPrimaryTextHover: '#FA541C',
        colorPrimaryTextActive: '#462786',
        colorSuccessBg: '#E8FBF4',
        colorSuccessBgHover: '#FA541C',
        colorSuccessBorder: '#C0E8DA',
        colorSuccessBorderHover: '#FA541C',
        colorSuccessHover: '#FA541C',
        colorSuccess: '#8dd9be',
        colorSuccessActive: '#FA541C',
        colorSuccessTextHover: '#FA541C',
        colorSuccessText: '#FA541C',
        colorSuccessTextActive: '#FA541C',
        colorWarningBg: '#FEF6E8',
        colorWarningBgHover: '#FA541C',
        colorWarningBorder: '#f7e1b5',
        colorWarningBorderHover: '#FA541C',
        colorWarningHover: '#FA541C',
        colorWarningActive: '#FA541C',
        colorWarningTextHover: '#FA541C',
        colorWarningText: '#FA541C',
        colorWarningTextActive: '#FA541C',
        colorErrorBgHover: '#3ebb00',
        colorErrorBorderHover: '#E73D4E',
        colorErrorHover: '#F35969',
        colorErrorActive: '#F35969',
        colorErrorTextHover: '#3ebb00',
        colorErrorText: '#3ebb00',
        colorErrorTextActive: '#3ebb00',
        colorError: '#F57A87',
        colorErrorBg: '#fff3f5',
        colorErrorBorder: '#FFD7DE',
        colorInfoBgHover: '#FA541C',
        colorInfoBorderHover: '#FA541C',

        // base <a> color
        colorInfoText: '#563599',
        colorInfoHover: '#563599',
        colorInfoActive: '#563599',

        colorInfoTextHover: '#FA541C',
        colorInfoTextActive: '#FA541C',
        colorInfoBg: '#ffffff',
        colorInfoBorder: '#CD93E1',
        colorInfo: '#CD93E1',
        colorText: '#1a1a1a',
        colorTextSecondary: '#000000',
        // Text for List.Meta description
        colorTextTertiary: '#1a1a1a',
        colorTextQuaternary: '#cccccc',
        colorBorder: '#dddddd',
        colorBorderSecondary: '#eeeeee',
        // skeleton
        colorFill: '#00000005',
        colorFillSecondary: '#5a5a5a1a',

        colorFillTertiary: '#ffffff',
        colorBgContainer: '#ffffff',
        colorBgElevated: '#ffffff',
        colorBgLayout: '#ffffff',
        colorBgSpotlight: '#372D3C',
        colorFillQuaternary: '#ffffff',
        fontSizeXL: 0,
        fontSizeHeading1: 0,
        fontSizeHeading2: 0,
        fontSizeHeading3: 24,
        fontSizeHeading4: 20,
        fontSizeHeading5: 16,
        lineHeight: 1.5,
        lineHeightLG: 1.5,
        lineHeightHeading1: 1.2,
        borderRadius: 2,
        borderRadiusXS: 2,
        colorBgMask: '#00000073',
        fontFamily:
            'SB Sans Text, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, Noto Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji',
    },
    components: {
        Button: {
            colorLink: '#563599',
            colorLinkActive: '#462786',
            colorLinkHover: '#462786',
            colorError: '#f57a87',
        },
        Typography: {
            colorLink: '#8D57A0',
            colorLinkActive: '#682E7C',
            colorLinkHover: '#682E7C',
            colorTextDisabled: '#d2bcd9',
            sizeMarginHeadingVerticalStart: 0,
            sizeMarginHeadingVerticalEnd: 0,
        },
        Slider: {
            colorPrimaryBorder: '#563599',
            colorFillContentHover: '#634E8F',
        },
        Select: {
            colorWarningHover: '#E49701',
            controlItemBgHover: '#F9F9F9',
        },
        Dropdown: {
            colorPrimaryBorder: '#FA541C',
            controlItemBgActiveHover: '#f4eef6',
            controlItemBgHover: '#f4eef6',
            colorText: '#8d57a0',
            controlItemBgActive: '#f4eef6',
        },
        DatePicker: {
            colorLink: '#563599',
            colorLinkActive: '#462786',
            colorLinkHover: '#462786',
        },
        Message: {
            colorInfo: '#cd93e1',
        },
        Segmented: {
            colorInfoBg: 'red',
            colorBgContainer: 'red',
            // color selected segment bg
            colorBgElevated: '#fff',
            // color of segmented bg
            colorBgLayout: '#fff',
        },
        Table: {
            colorFillAlter: '#f4eef6',
        },
        Alert: {},
        Skeleton: {},
    },
};
